name: CICD

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        pyspark-version: ["3.*", "4.0.0"]
        include:
          - pyspark-version: "3.*"
            java-version: "11" # PySpark 3.x works well with Java 8 or 11
          - pyspark-version: "4.0.0"
            java-version: "17" # PySpark 4.x requires Java 17+

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ./.pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-precommit-${{ matrix.python-version }}-
            ${{ runner.os }}-precommit-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: Install dependencies
        run: uv sync --extra test --locked
        env:
          PYTHONPATH: src # Ensure src is in the PYTHONPATH

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

      - name: Run pytest
        env:
          SPARK_LOCAL_IP: 127.0.0.1
          PYTHONPATH: src # Ensure src is in the PYTHONPATH
        run: uv run --with "pyspark==${{ matrix.pyspark-version }}" pytest
